version: '3'

# Define services
services:
  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      # Use an image built from the specified dockerfile in the current directory.
      context: .
      # Load docker file
      dockerfile: Dockerfile